# Generated by Django 4.2.11 on 2024-04-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=32, verbose_name='部门名字')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='员工姓名')),
                ('password', models.CharField(max_length=64, verbose_name='员工个人密码')),
                ('age', models.IntegerField(verbose_name='员工年龄')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='员工薪资')),
                ('create_time', models.DateTimeField(verbose_name='员工入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='员工性别')),
                ('user_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManage.department')),
            ],
        ),
    ]
