# Generated by Django 4.2.11 on 2024-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0003_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月租'),
        ),
    ]
