# Generated by Django 4.2.11 on 2024-04-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, verbose_name='订单号')),
                ('order_name', models.CharField(max_length=32, verbose_name='订单名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '已支付')], verbose_name='状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManage.admin', verbose_name='管理员')),
            ],
        ),
    ]
