# Generated by Django 4.2.11 on 2024-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0008_uploadinfo_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadInfo_ModalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('file', models.FileField(max_length=128, upload_to='', verbose_name='上传的文件')),
            ],
        ),
        migrations.RenameModel(
            old_name='UploadInfo',
            new_name='UploadInfo_Form',
        ),
    ]
